version: '3.1'
services:
  database:
    image: mariadb:10.8
    container_name: db_container
    volumes:
      - ${BACKUP_DB}:/docker-entrypoint-initdb.d/
      - data:/var/lib/mysql
      - type: bind
        source: ${DATALAKE_PATH}
        target: /home/datalake
    networks:
      - network
    ports:
      - ${PORT}:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
networks:
  network:
    driver: bridge
volumes:
  data: