version: '3.1'
services:
  database:
    image: mariadb:10.8
    container_name: db_container
    volumes:
      - ${BACKUP_DB}:/docker-entrypoint-initdb.d/
      - data:/var/lib/mysql
      - type: bind
        source: ${DATALAKE_PATH}
        target: /usr/src/app/datalake
    networks:
      - connect_network
      #- airflow_default
    ports:
      - ${PORT}:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
networks:
  # airflow_default:
  #   external: true
  connect_network:
    driver: bridge
volumes:
  data: